### ISSUE TITLE
Nothing displaying

### ISSUE THREAD

**Issue by kleinjm** [kristijanhusak/tmux-simple-git-status#1]
Here's a branch on my dotfiles with the addition of this plugin https://github.com/kleinjm/dotfiles/compare/git_status

![image](https://user-images.githubusercontent.com/2565158/49329682-9ae9c300-f550-11e8-945d-39c73d60baf4.png)

I'm not seeing anything with local changes.
```
git version 2.19.1
tmux 2.8
OSX Mojave 10.14.1
```

**Comment by Falkgaard** [comment]
Same here.

**Comment by RocKordier** [comment]
Little late but I had the same problems today. As i can see in your screenshot @kleinjm you've installed some plugins for tmux (https://github.com/gpakosz/.tmux maybe)?

The default config modifies `base-index` and `pane-base-index` to `1`
You can change settings in your `~/.tmux.conf.local` to:
```
set -g base-index 0
setw -g pane-base-index 0
```
so everything should works again.
